const ACTIONS = {
  LOGIN: "LOGIN",
  GET_TOKEN: "GET_TOKEN",
  REMOVE_TOKEN: "REMOVE_TOKEN",
  GET_USER: "GET_USER",
  GET_ALL_USERS: "GET_ALL_USERS",
  GET_ROLES:'GET_ROLES'
};

export default ACTIONS;
